### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by smmoosavi** [msavin/Mongol#82]
Can you support yaml. Yaml is more human readable and less `"` make it easy to write. Every json string is yaml and converting between them is easy.
[js-yaml](https://github.com/nodeca/js-yaml) can help you.

``` yml
_id: 'slkjd4j2lkd'
firstname: Ali
lastname: Alavi
age: 29
emails: 
  - ali@gmail.com
  - ali@yahoo.com
```

Is equeal:

``` json
{
  "_id": "slkjd4j2lkd",
  "firstname": "Ali",
  "lastname": "Alavi",
  "age": 29,
  "emails": [
    "ali@gmail.com",
    "ali@yahoo.com"
  ]
}
```
